{
 "title": "Nginx Overview",
 "tags": [
  "hexlet",
  "observability",
  "nginx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(nginx_up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nginx_up{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(nginx_up{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "nginx_up"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_active{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{job=~\"$job\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "NGINX requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(nginx_http_requests_total{job=~\"$job\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (nginx_connections_active{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "active {{instance}}"
    }
   ]
  },
  {
   "title": "Connections by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (nginx_connections_reading{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "reading {{instance}}"
    },
    {
     "expr": "sum by (instance) (nginx_connections_writing{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "writing {{instance}}"
    },
    {
     "expr": "sum by (instance) (nginx_connections_waiting{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "waiting {{instance}}"
    }
   ]
  }
 ]
}