variable "cloud_id" {
  description = "Yandex Cloud cloud ID."
  type        = string

  validation {
    condition     = length(trimspace(var.cloud_id)) > 0
    error_message = "cloud_id must not be empty."
  }
}

variable "folder_id" {
  description = "Yandex Cloud folder ID where resources will be created."
  type        = string

  validation {
    condition     = length(trimspace(var.folder_id)) > 0
    error_message = "folder_id must not be empty."
  }
}

variable "zone" {
  description = "Availability zone for the zonal cluster, worker and PostgreSQL host."
  type        = string
  default     = "ru-central1-a"
}

variable "project_name" {
  description = "Prefix used in names and labels."
  type        = string
  default     = "project-319"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{1,30}[a-z0-9]$", var.project_name))
    error_message = "project_name must contain only lowercase Latin letters, digits and hyphens."
  }
}

variable "environment" {
  description = "Environment label."
  type        = string
  default     = "production"
}

variable "admin_cidrs" {
  description = "Public IPv4 CIDRs allowed to connect to the Kubernetes API, normally your current IP/32."
  type        = list(string)

  validation {
    condition     = length(var.admin_cidrs) > 0 && alltrue([for cidr in var.admin_cidrs : can(cidrnetmask(cidr))])
    error_message = "admin_cidrs must contain at least one valid IPv4 CIDR."
  }
}

variable "subnet_cidr" {
  description = "IPv4 CIDR of the private infrastructure subnet."
  type        = string
  default     = "10.20.0.0/24"

  validation {
    condition     = can(cidrnetmask(var.subnet_cidr))
    error_message = "subnet_cidr must be a valid IPv4 CIDR."
  }
}

variable "cluster_ipv4_range" {
  description = "CIDR used for Kubernetes pods."
  type        = string
  default     = "10.112.0.0/16"
}

variable "service_ipv4_range" {
  description = "CIDR used for Kubernetes services."
  type        = string
  default     = "10.96.0.0/16"
}

variable "node_count" {
  description = "Fixed number of worker nodes."
  type        = number
  default     = 2

  validation {
    condition     = var.node_count >= 2
    error_message = "node_count must be at least 2 for zero-downtime releases."
  }
}

variable "node_platform_id" {
  description = "Compute platform for worker nodes."
  type        = string
  default     = "standard-v3"
}

variable "node_cores" {
  description = "Number of vCPU cores per worker."
  type        = number
  default     = 2
}

variable "node_memory_gb" {
  description = "RAM in GiB per worker."
  type        = number
  default     = 4
}

variable "node_core_fraction" {
  description = "Guaranteed vCPU share for a worker."
  type        = number
  default     = 20
}

variable "node_disk_size_gb" {
  description = "Worker boot disk size in GiB. Managed Kubernetes requires at least 64 GiB."
  type        = number
  default     = 64

  validation {
    condition     = var.node_disk_size_gb >= 64
    error_message = "node_disk_size_gb must be at least 64."
  }
}

variable "node_preemptible" {
  description = "Use a preemptible worker. Disabled by default for predictable availability."
  type        = bool
  default     = false
}

variable "postgresql_version" {
  description = "Managed PostgreSQL major version."
  type        = string
  default     = "17"
}

variable "postgresql_resource_preset_id" {
  description = "Managed PostgreSQL host class. b1.medium is intended for test workloads."
  type        = string
  default     = "b1.medium"
}

variable "postgresql_disk_type_id" {
  description = "Managed PostgreSQL disk type."
  type        = string
  default     = "network-hdd"
}

variable "postgresql_disk_size_gb" {
  description = "Managed PostgreSQL disk size in GiB."
  type        = number
  default     = 10
}

variable "postgresql_database" {
  description = "Application database name."
  type        = string
  default     = "bulletins"
}

variable "postgresql_username" {
  description = "Application database user. The password is generated by Terraform."
  type        = string
  default     = "bulletins"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.postgresql_username))
    error_message = "postgresql_username must be a valid lowercase PostgreSQL role name."
  }
}

variable "app_bucket_name" {
  description = "Globally unique application bucket name. If null, Terraform creates a name with a random suffix."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition = var.app_bucket_name == null ? true : can(regex(
      "^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$",
      var.app_bucket_name,
    ))
    error_message = "app_bucket_name must be a valid 3-63 character Object Storage bucket name."
  }
}

variable "app_bucket_max_size_bytes" {
  description = "Maximum application bucket size in bytes."
  type        = number
  default     = 1073741824
}

variable "deletion_protection" {
  description = "Enable deletion protection for PostgreSQL and Lockbox after the training environment is stable."
  type        = bool
  default     = false
}

variable "logging_retention_period" {
  description = "Cloud Logging retention period for application pod logs."
  type        = string
  default     = "168h"

  validation {
    condition     = can(regex("^[1-9][0-9]*h$", var.logging_retention_period))
    error_message = "logging_retention_period must be a positive duration in hours, for example 168h."
  }
}

variable "prometheus_workspace_id" {
  description = "Managed Service for Prometheus workspace ID. Create the workspace once in Yandex Monitoring before deploying the in-cluster collector."
  type        = string
  default     = ""

  validation {
    condition     = var.prometheus_workspace_id == "" || can(regex("^[a-z0-9]+$", var.prometheus_workspace_id))
    error_message = "prometheus_workspace_id must be empty or contain a valid Yandex Cloud resource ID."
  }
}
