apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bulletin-board.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bulletin-board.labels" . | nindent 4 }}
data:
  {{- range $key := keys .Values.config | sortAlpha }}
  {{ $key }}: {{ index $.Values.config $key | toString | quote }}
  {{- end }}

