apiVersion: v1
kind: Service
metadata:
  name: bulletins-public
  namespace: bulletins
  labels:
    app.kubernetes.io/name: bulletins
    app.kubernetes.io/component: application
  annotations:
    yandex.cloud/load-balancer-healthcheck-healthy-threshold: "2"
    yandex.cloud/load-balancer-healthcheck-interval: 2s
    yandex.cloud/load-balancer-healthcheck-timeout: 1s
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: bulletins
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
