apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: project-319-lockbox
  labels:
    app.kubernetes.io/name: project-319-lockbox
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: bulletins
spec:
  conditions:
    - namespaces:
        - bulletins
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: sa-creds
          namespace: external-secrets-operator-space
          key: key
