---
nginx_exporter_container_name: nginx-prometheus-exporter
nginx_exporter_check_address: 127.0.0.1
nginx_exporter_restart_policy: unless-stopped
nginx_exporter_scrape_uri: >-
  http://127.0.0.1:{{ monitoring_proxy_port }}{{ nginx_stub_status_path }}
